name: Node.js CI

on:
  push:
    branches: ["main", "prod"]
  pull_request:
    branches: ["main", "prod"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        branch-path: [main, prod]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present

      - name: Deploy to gh-pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          mkdir -p deploy/${{ matrix.branch-path }}
          cp -r build/* deploy/${{ matrix.branch-path }}/
          cd deploy
          git init
          git add .
          git commit -m "Deploy to GitHub Pages for ${{ matrix.branch-path }} branch"
          git push --force origin master:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
