name: Node.js CI

on:
  push:
    branches: ["main", "prod"]
  pull_request:
    branches: ["main", "prod"]

permissions:
  contents: write

jobs:
  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy to gh-pages for main
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          mkdir -p build/main
          mv build/* build/main/
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy to gh-pages for prod
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          mkdir -p build/prod
          mv build/* build/prod/
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
